import { Property } from '@/types'

export const mockProperties: Property[] = [
    {
        id: '1',
        user_id: 'mock',
        title: 'Casa con jardín',
        description: null,
        price: 95000,
        currency: 'USD',
        type: 'casa',
        operation: 'venta',
        address: 'Gral. Paz, Córdoba',
        neighborhood: 'General Paz',
        neighborhood_id: null,
        lat: -31.4050,
        lng: -64.1950,
        bedrooms: 3,
        bathrooms: 2,
        area_m2: 90,
        status: 'active',
        created_at: new Date().toISOString(),
    },
    {
        id: '2',
        user_id: 'mock',
        title: 'Departamento céntrico',
        description: null,
        price: 120000,
        currency: 'USD',
        type: 'departamento',
        operation: 'venta',
        address: 'Nueva Córdoba',
        neighborhood: 'Nueva Córdoba',
        neighborhood_id: null,
        lat: -31.4200,
        lng: -64.1850,
        bedrooms: 2,
        bathrooms: 1,
        area_m2: 65,
        status: 'active',
        created_at: new Date().toISOString(),
    },
    {
        id: '3',
        user_id: 'mock',
        title: 'Casa amplia',
        description: null,
        price: 145000,
        currency: 'USD',
        type: 'casa',
        operation: 'venta',
        address: 'Cerro de las Rosas',
        neighborhood: 'Cerro de las Rosas',
        neighborhood_id: null,
        lat: -31.3900,
        lng: -64.2100,
        bedrooms: 4,
        bathrooms: 3,
        area_m2: 180,
        status: 'active',
        created_at: new Date().toISOString(),
    },
    {
        id: '4',
        user_id: 'mock',
        title: 'Terreno en venta',
        description: null,
        price: 55000,
        currency: 'USD',
        type: 'terreno',
        operation: 'venta',
        address: 'Villa Cabrera',
        neighborhood: 'Villa Cabrera',
        neighborhood_id: null,
        lat: -31.3800,
        lng: -64.1750,
        bedrooms: null,
        bathrooms: null,
        area_m2: 300,
        status: 'active',
        created_at: new Date().toISOString(),
    },
    {
        id: '5',
        user_id: 'mock',
        title: 'Local comercial',
        description: null,
        price: 85000,
        currency: 'USD',
        type: 'local',
        operation: 'venta',
        address: 'Alberdi, Córdoba',
        neighborhood: 'Alberdi',
        neighborhood_id: null,
        lat: -31.4100,
        lng: -64.2050,
        bedrooms: null,
        bathrooms: 1,
        area_m2: 120,
        status: 'active',
        created_at: new Date().toISOString(),
    },
]